version: "3"
services:
  web:
    container_name: dockerbackend
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - app_data:/app
    depends_on:
      - mongo
    links:
      - mongo  
  mongo:
    container_name: mongobackend
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/database/mongodb

volumes:
  app_data:
  mongo_data:
